### ISSUE TITLE
To-do list for exploratory spike

### ISSUE THREAD

**Issue by levity** [Hylozoic/HyloReactNative#1]
- [x] Read through "The Basics" in [React Native docs](https://facebook.github.io/react-native/docs/getting-started.html)
- [x] Run in iOS simulator
- [x] Run in Android simulator
- [x] Access GraphQL API
- [x] Make tests pass
- [x] Configure via environment variables
- [x] Set up dev environment for a second person
- [x] Get a build onto an iOS device
- [x] Get a build onto an Android device
