### ISSUE TITLE
Make sure MixPanel is tracking everything needed by Zebras Unite

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/HyloReactNative#629]
- [ ] # of members in the group over time

- [ ]  # of "contributing" members over time: weekly/monthly - have engaged in an activity such as create a post, RSVPed for an event, or commented on a post (Question: does this include reacting on a post?)

- [ ] # of daily, weekly, and monthly "active" members - have logged in to the platform

- [ ] % retention rate (7 day, 30 day) - Question: how to define retention

- [ ] # of posts: daily/weekly/monthly - broken down by type

- [ ] % member vs moderator posts

- [ ] # of post clicks

- [ ] # of comments

- [ ] # post & comment reactions

- [ ] # of event RSVPs

- [ ] View top posts, ranked

- [ ] View top active members, ranked

- [ ] Track every step of the signup flow for our funnel analysis
